/**:
  ros__parameters:
    network:
      config: "$(find-pkg-share openrobotics_darknet_ros)/config/yolo-v4-tiny/yolov4-tiny.cfg"
      weights: "$(find-pkg-share openrobotics_darknet_ros)/config/yolo-v4-tiny/yolov4-tiny.weights"
      class_names: "$(find-pkg-share openrobotics_darknet_ros)/config/yolo-v4-tiny/coco.names"
    detection:
      threshold: 0.25
      nms_threshold: 0.45
